# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df9f8a3e995212ed6755e864db99a5a25f401fbca3341033dc143cf273397c8f5d6d5c3ff85ba63557823d7018c812bf2b65b49670f65fe055b21adeebb2479c

test:
  secret_key_base: 87dc12bb1c3357fc01fbedf2b10cf895779dd41d22d273498cbccdbfe2337e39f0976183b3f0b33de5503f463dc61fcd04766c03cf10f2b39b29991b799726fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
